### ISSUE TITLE
Serialization does not work for maps with Enum keys

### ISSUE THREAD

**Issue by Jezorko** [vert-x3/vertx-amqp-bridge#23]
Minimal example (requires a queue listening for AMQP connections on port `5672`):

```java
import io.vertx.amqpbridge.AmqpBridgeOptions;
import io.vertx.amqpbridge.AmqpConstants;
import io.vertx.core.json.JsonObject;
import io.vertx.core.logging.Logger;
import io.vertx.core.logging.LoggerFactory;
import io.vertx.reactivex.amqpbridge.AmqpBridge;
import io.vertx.reactivex.core.Vertx;

import java.util.Collections;

public class MessageTranslatorEnumExceptionExample {

    private enum TestEnum {
        TEST_ENUM_KEY
    }

    public static void main(String... args) {
        Vertx vertx = Vertx.vertx();
        Logger log = LoggerFactory.getLogger("main");

        AmqpBridge.create(vertx,
                          new AmqpBridgeOptions().setSsl(false)
                                                 .setConnectTimeout(3000))
                  .rxStart("localhost", 5672, "admin", "admin")
                  .map(bridge -> bridge.createProducer("test-queue"))
                  .doOnSuccess(producer -> {
                      log.info("sending message");
                      producer.send(new JsonObject().put(AmqpConstants.BODY, getExampleMessageBodyWithEnum()));
                      log.info("message sent!");
                  })
                  .doFinally(vertx::close)
                  .subscribe(ok -> log.info("all good"),
                             error -> log.error("something went wrong", error));
    }

    private static JsonObject getExampleMessageBodyWithEnum() {
        return JsonObject.mapFrom(Collections.singletonMap(TestEnum.TEST_ENUM_KEY, "test"));
    }

    private static JsonObject getExampleMessageBodyWithString() {
        return JsonObject.mapFrom(Collections.singletonMap(TestEnum.TEST_ENUM_KEY.name(), "test"));
    }

    private static JsonObject getExampleMessageBodyWithEnumTwiceSerialized() {
        return new JsonObject(JsonObject.mapFrom(Collections.singletonMap(TestEnum.TEST_ENUM_KEY, "test"))
                                        .encode());
    }

}
```

Expected outcome: the message is properly serialized and sent to the queue.

Actual outcome: the following exception is thrown:
```
java.lang.NullPointerException
	at org.apache.qpid.proton.codec.MapType.calculateSize(MapType.java:89)
	at org.apache.qpid.proton.codec.MapType.getEncoding(MapType.java:65)
	at org.apache.qpid.proton.codec.MapType.getEncoding(MapType.java:29)
	at org.apache.qpid.proton.codec.AbstractPrimitiveType.write(AbstractPrimitiveType.java:27)
	at org.apache.qpid.proton.codec.EncoderImpl.writeMap(EncoderImpl.java:588)
	at org.apache.qpid.proton.codec.EncoderImpl.writeUnregisteredType(EncoderImpl.java:759)
	at org.apache.qpid.proton.codec.EncoderImpl.writeObject(EncoderImpl.java:738)
	at org.apache.qpid.proton.codec.messaging.FastPathAmqpValueType.write(FastPathAmqpValueType.java:97)
	at org.apache.qpid.proton.codec.messaging.FastPathAmqpValueType.write(FastPathAmqpValueType.java:33)
	at org.apache.qpid.proton.codec.EncoderImpl.writeObject(EncoderImpl.java:734)
	at org.apache.qpid.proton.message.impl.MessageImpl.encode(MessageImpl.java:740)
	at io.vertx.proton.impl.ProtonSenderImpl.send(ProtonSenderImpl.java:88)
	at io.vertx.proton.impl.ProtonSenderImpl.send(ProtonSenderImpl.java:56)
	at io.vertx.proton.impl.ProtonSenderImpl.send(ProtonSenderImpl.java:51)
	at io.vertx.amqpbridge.impl.AmqpProducerImpl.lambda$doSend$3(AmqpProducerImpl.java:140)
	at io.vertx.amqpbridge.impl.AmqpBridgeImpl.runOnContext(AmqpBridgeImpl.java:326)
	at io.vertx.amqpbridge.impl.AmqpProducerImpl.doSend(AmqpProducerImpl.java:134)
	at io.vertx.amqpbridge.impl.AmqpProducerImpl.send(AmqpProducerImpl.java:111)
	at io.vertx.amqpbridge.impl.AmqpProducerImpl.send(AmqpProducerImpl.java:106)
	at io.vertx.amqpbridge.impl.AmqpProducerImpl.send(AmqpProducerImpl.java:32)
	at io.vertx.reactivex.core.eventbus.MessageProducer.send(MessageProducer.java:141)
	at uk.co.MessageTranslatorEnumExceptionExample.lambda$main$1(MessageTranslatorEnumExceptionExample.java:30)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:54)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.vertx.reactivex.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:52)
	at io.vertx.reactivex.amqpbridge.AmqpBridge$1.handle(AmqpBridge.java:104)
	at io.vertx.reactivex.amqpbridge.AmqpBridge$1.handle(AmqpBridge.java:101)
	at io.vertx.amqpbridge.impl.AmqpBridgeImpl.lambda$null$3(AmqpBridgeImpl.java:146)
	at io.vertx.proton.impl.ProtonLinkImpl.fireRemoteOpen(ProtonLinkImpl.java:314)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:138)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:386)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:235)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:125)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:364)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Note that this only fails when the input map's keys are enum values.
If you use `getExampleMessageBodyWithString` or `getExampleMessageBodyWithEnumTwiceSerialized` instead, it should work perfectly fine.

This exception in minimal example is different from my colleague's for some reason. He is getting `ClassCastException` in the application, coming this line: https://github.com/vert-x3/vertx-amqp-bridge/blob/3.7/src/main/java/io/vertx/amqpbridge/impl/MessageTranslatorImpl.java#L354
(`MessageTranslatorImpl` is assuming the map keys are `String`s).

Vert.x and bridge version we are using is `3.7.1`.

**Comment by gemmellr** [comment]
The amqp-bridge is deprecated and will be removed in Vert.x 4, so I would not suggest it be used for new work, use either the newer https://github.com/vert-x3/vertx-amqp-client, or https://github.com/vert-x3/vertx-proton upon which both others are built.

The exception presumably thrown is because the underlying AMQP encoder in proton-j does not know how to encode your arbitrary enum class type as an AMQP type, and so fell over while trying to determine the encoded size of the map.

The JsonObject is being used by the bridge essentially as a wrapper here, the bridge does not perform any encode/decode on it, relying on those that you or the JsonObject itself do (such as creating from a string like your 3rd example, which presumably changed the key type). The bridge performs some minimal change during translation such as JsonArray into a List but thats it, types are otherwise essentially passed through as they arrive, so it has no way to handle an enum. There is no Java serialization occurring here either for example, so sending an enum is not going to result in an enum appearing on the other side if thats what you wanted. For that type of thing you would need to [de]serialize things yourself, e.g sending a string value or even a data body section with binary.
